---
apiVersion: v1
kind: Template
name: ${NAME}-config-template
labels:
  app: ${NAME}
  app.kubernetes.io/component: ${NAME}
  app.kubernetes.io/name: ${NAME}
  app.kubernetes.io/managed-by: template
  app.kubernetes.io/part-of: ${NAME}
  app.kubernetes.io/version: "6"
  template: ${NAME}-secret-template
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ${NAME}-config
    data:
      config.js: |-
        // runtime-config.js vars
          window["_env_"] =  {
            "NODE_ENV": "production",
            "REACT_APP_CLIENT_ROLE": "formsflow-client",
            "REACT_APP_STAFF_DESIGNER_ROLE": "formsflow-designer",
            "REACT_APP_STAFF_REVIEWER_ROLE": "formsflow-reviewer",
            "REACT_APP_CLIENT_ID": "${REACT_APP_CLIENT_ID}",
            "REACT_APP_STAFF_REVIEWER_ID": "${REACT_APP_STAFF_REVIEWER_ID}",
            "REACT_APP_STAFF_DESIGNER_ID": "${REACT_APP_STAFF_DESIGNER_ID}",
            "REACT_APP_USER_RESOURCE_FORM_ID": "${REACT_APP_USER_RESOURCE_FORM_ID}",
            "REACT_APP_API_SERVER_URL": "${REACT_APP_API_SERVER_URL}",
            "REACT_APP_API_PROJECT_URL": "${REACT_APP_API_PROJECT_URL}",
            "REACT_APP_CAMUNDA_API_URI": "${REACT_APP_CAMUNDA_API_URI}",
            "REACT_APP_KEYCLOAK_CLIENT": "forms-flow-web",
            "REACT_APP_WEB_BASE_URL": "${REACT_APP_WEB_BASE_URL}",
            "REACT_APP_ANONYMOUS_ID": "${REACT_APP_ANONYMOUS_ID}",
            "REACT_APP_WEBSOCKET_ENCRYPT_KEY": "{REACT_APP_WEBSOCKET_ENCRYPT_KEY}",
            "REACT_APP_KEYCLOAK_URL_REALM": "${REALM}",
            "REACT_APP_KEYCLOAK_URL": "${REACT_APP_KEYCLOAK_URL}",
            "REACT_APP_APPLICATION_NAME": "${REACT_APP_APPLICATION_NAME}",
            "REACT_APP_WEB_BASE_CUSTOM_URL": "${REACT_APP_WEB_BASE_CUSTOM_URL}",
            "REACT_APP_FORMIO_JWT_SECRET": "${REACT_APP_FORMIO_JWT_SECRET}",
            "REACT_APP_USER_ACCESS_PERMISSIONS": '${REACT_APP_USER_ACCESS_PERMISSIONS}'
          }
  -
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ${NAME}-keycloak-config
    data:
      keycloak.json: |-
        {
        "realm": "${REALM}",
        "auth-server-url": "${AUTH_SERVER_URL}" ,
        "ssl-required": "external",
        "resource": "forms-flow-web",
        "public-client": true,
        "verify-token-audience": true,
        "use-resource-role-mappings": true,
        "confidential-port": 0
        }
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the OpenShift resources associated to the
      server instance.
    required: true
    value: forms-flow-web
  - name: REACT_APP_KEYCLOAK_URL
    displayName: REACT_APP_KEYCLOAK_URL
    description: keycloak url without auth part in the url
    required: true
  - name: REACT_APP_APPLICATION_NAME
    displayName: REACT_APP_APPLICATION_NAME
    description: the name displayed in the application home page
    required: true
  - name: REACT_APP_USER_ACCESS_PERMISSIONS
    displayName: REACT_APP_USER_ACCESS_PERMISSIONS
    description: JSON formatted permissions to enable / disable few access on user login
    required: true
  - name: REACT_APP_WEB_BASE_CUSTOM_URL
    displayName: REACT_APP_WEB_BASE_CUSTOM_URL
    description: Clients can use this env variable to provide their custom URL
    required: false
  - name: REACT_APP_FORMIO_JWT_SECRET
    displayName: REACT_APP_FORMIO_JWT_SECRET
    description: FORMIO JWT Secret
    required: false
  - name: DESIGNER_ROLE_ID
    displayName: DESIGNER_ROLE_ID
    description: Desginer access role id
    required: false
  - name: REACT_APP_CLIENT_ID
    displayName: REACT_APP_CLIENT_ID
    description:
      Route to access Forms Flow AI Web site
    required: true
  - name: REACT_APP_STAFF_REVIEWER_ID
    displayName: REACT_APP_STAFF_REVIEWER_ID
    description:
      Route to access Forms Flow AI Web site
    required: true
  - name: REACT_APP_STAFF_DESIGNER_ID
    displayName: REACT_APP_STAFF_DESIGNER_ID
    description:
      Route to access Forms Flow AI Web site
    required: true
  - name: REACT_APP_USER_RESOURCE_FORM_ID
    displayName: REACT_APP_USER_RESOURCE_FORM_ID
    description:
      Route to access Forms Flow AI Web site
    required: true
  - name: REACT_APP_ANONYMOUS_ID
    displayName: REACT_APPREACT_APP_ANONYMOUS_ID_CLIENT_ID
    description:
      Route to access Forms Flow AI Web site
    required: true
  - name: REACT_APP_WEB_BASE_URL
    displayName: REACT_APP_WEB_BASE_URL
    description:
      Route to access Forms Flow AI Web site
    required: true
  - name: REACT_APP_CAMUNDA_API_URI
    displayName: REACT_APP_CAMUNDA_API_URI
    description:
      Route to access Forms Flow AI Web site
    required: true
  - name: REACT_APP_API_PROJECT_URL
    displayName: REACT_APP_API_PROJECT_URL
    description:
      Route to access Forms Flow AI Web site
    required: true
  - name: REACT_APP_API_SERVER_URL
    displayName: REACT_APP_API_SERVER_URL
    description:
      Route to access Forms Flow AI Web site
    required: true
  - name: REACT_APP_WEBSOCKET_ENCRYPT_KEY
    displayName: REACT_APP_WEBSOCKET_ENCRYPT_KEY
    description:
    required: true
  - name: AUTH_SERVER_URL
    displayName: AUTH_SERVER_URL
    description: Authentication server Url
    required: true
  - name: REALM
    displayName: REALM
    description: oidc REALM
    required: true
